-- NOTE: Samtone is a theme inspired from charmbracelet and created by me

local M = {}
M.base_30 = {
  white = "#d4b8dc",
  black = "#0f0d13",
  darker_black = "#0f0d13",
  black2 = "#16131b",
  one_bg = "#16131b",
  one_bg2 = "#1c1822",
  one_bg3 = "#221c2c",
  grey = "#50406b",
  grey_fg = "#50406b",
  grey_fg2 = "#858392", -- Squid  CharmTone
  light_grey = "#BFBCC8", -- Smoke  CharmTone
  red = "#f27ec4",
  baby_pink = "#FF84FF", -- Blush  CharmTone
  pink = "#f27ec4",
  line = "#221c2c",
  green = "#00b875", -- NeueGuac  CharmTone
  vibrant_green = "#00FFB2", -- Julep  CharmTone (brightest green)
  nord_blue = "#8B75FF", -- Hazy  CharmTone
  blue = "#7272FF", -- Guppy  CharmTone
  seablue = "#00A4FF", -- Malibu  CharmTone
  yellow = "#f2f27e",
  sun = "#f2987e",
  purple = "#b37ef2",
  dark_purple = "#50406b",
  teal = "#0ADCD9", -- Turtle  CharmTone
  orange = "#f2987e",
  cyan = "#5CDFEA", -- Lichen  CharmTone
  statusline_bg = "#16131b",
  lightbg = "#1c1822",
  pmenu_bg = "#221c2c",
  folder_bg = "#C259FF", -- Violet  CharmTone
}

M.base_16 = {
  base00 = "#0f0d13",
  base01 = "#16131b",
  base02 = "#1c1822",
  base03 = "#50406b",
  base04 = "#858392", -- Squid  CharmTone
  base05 = "#d4b8dc",
  base06 = "#DFDBDD", -- Ash  CharmTone
  base07 = "#F1EFEF", -- Salt  CharmTone
  base08 = "#f27ec4",
  base09 = "#f2987e",
  base0A = "#f2f27e",
  base0B = "#00b875", -- NeueGuac  CharmTone
  base0C = "#0ADCD9", -- Turtle  CharmTone
  base0D = "#7272FF", -- Guppy  CharmTone
  base0E = "#b37ef2",
  base0F = "#f27ec4",
}

M.extras = {
  light_blue = "#7272FF",
  lighter_blue = "#8B75FF",
  keyword_purple = "#b37ef2",
  lighter_blue_builtin = "#4FBEFE",
  diff_dark_green = "#1C3634",
  diff_dark_red = "#1b1318",
  diff_dark_blue = "#13131b",
  diff_dark_grey = "#16131b",
  diff_dark_blue2 = "#221c2c",
}

local C = M.base_30
local E = M.extras
M.polish_hl = {
  defaults = {
    LineNr = { fg = C.grey },
    CursorLineNr = { fg = C.purple, bold = true },
    Search = { fg = C.white, bg = C.one_bg3 },
    IncSearch = { fg = C.black, bg = C.purple },
    CurSearch = { fg = C.black, bg = C.purple },
    Substitute = { fg = C.white, bg = C.one_bg3 },
    DiffAdd = { bg = E.diff_dark_green, fg = C.vibrant_green },
    DiffDelete = { bg = E.diff_dark_red, fg = C.pink },
    DiffChange = { bg = E.diff_dark_blue, fg = C.cyan },
    DiffText = { bg = E.diff_dark_blue2, fg = C.baby_pink, bold = true },
    DiffviewDiffAdd = { bg = E.diff_dark_green, fg = C.vibrant_green },
    DiffviewDiffDelete = { bg = E.diff_dark_red, fg = E.diff_dark_red },
    DiffviewDiffChange = { bg = E.diff_dark_grey, fg = C.cyan },
    DiffviewDiffText = { bg = E.diff_dark_blue2, fg = C.baby_pink, bold = true },
    DiffAddAsDelete = { bg = E.diff_dark_red, fg = C.pink },
    DiffDeleteText = { bg = E.diff_dark_red, fg = C.pink },
    DiffChangeDelete = { bg = E.diff_dark_grey, fg = C.cyan },
    GitSignsAdd = { fg = C.vibrant_green },
    GitSignsChange = { fg = C.cyan },
    GitSignsDelete = { fg = C.pink },
  },
  treesitter = {
    ["@comment"] = { fg = C.dark_purple, italic = true },
    ["@keyword"] = { fg = C.purple },
    ["@keyword.function"] = { fg = C.purple },
    ["@function"] = { fg = C.yellow },
    ["@function.builtin"] = { fg = C.yellow },
    ["@string"] = { fg = C.sun },
    ["@number"] = { fg = C.orange },
    ["@boolean"] = { fg = C.orange },
    ["@type"] = { fg = C.cyan },
    ["@constant"] = { fg = C.orange },
    ["@property"] = { fg = C.white },
    ["@variable"] = { fg = C.white },
    ["@variable.builtin"] = { fg = C.orange },
    ["@punctuation.bracket"] = { fg = C.pink },
    -- Python-specific Tree-sitter highlights
    ["@keyword.import.python"] = { fg = C.purple, italic = true },
    ["@keyword.global.python"] = { fg = C.purple, italic = true },
    ["@keyword.return.python"] = { fg = C.purple, bold = true },
    ["@keyword.python"] = { fg = C.purple, italic = true },
    ["@keyword.function.python"] = { fg = C.purple, italic = true },
    ["@class.python"] = { fg = C.cyan },
    ["@type.python"] = { fg = C.cyan },
    ["@type.builtin.python"] = { fg = C.teal },
    ["@constructor.python"] = { fg = C.pink, bold = true },
    ["@function.python"] = { fg = C.yellow },
    ["@function.builtin.python"] = { fg = C.cyan, italic = true },
    ["@function.call.python"] = { fg = C.yellow },
    ["@variable.parameter.python"] = { fg = C.pink },
    ["@variable.member.python"] = { fg = C.white },
    ["@variable.builtin.python"] = { fg = C.orange, italic = true },
    ["@field.python"] = { fg = C.white },
    ["@property.python"] = { fg = C.white },
    ["@string.python"] = { fg = C.sun },
    ["@string.doc.python"] = { fg = C.dark_purple, italic = true },
    ["@constant.python"] = { fg = C.orange },
    ["@constant.builtin.python"] = { fg = C.orange },
    ["@number.python"] = { fg = C.orange },
    ["@boolean.python"] = { fg = C.orange },
    ["@operator.python"] = { fg = C.purple },
    ["@punctuation.delimiter.python"] = { fg = C.purple },
    ["@exception.python"] = { fg = C.pink, bold = true },
    ["@conditional.python"] = { fg = C.purple },
    ["@repeat.python"] = { fg = C.purple },
    -- Java-specific Tree-sitter highlights
    ["@keyword.import.java"] = { fg = C.purple, italic = true },
    ["@keyword.package.java"] = { fg = C.purple, italic = true },
    ["@keyword.return.java"] = { fg = C.purple, bold = true },
    ["@keyword.java"] = { fg = C.purple, italic = true },
    ["@keyword.modifier.java"] = { fg = C.purple, italic = true },
    ["@class.java"] = { fg = C.cyan },
    ["@interface.java"] = { fg = C.cyan, italic = true },
    ["@type.java"] = { fg = C.cyan },
    ["@type.builtin.java"] = { fg = C.teal },
    ["@constructor.java"] = { fg = C.pink, bold = true },
    ["@method.call.java"] = { fg = C.yellow },
    ["@function.method.java"] = { fg = C.yellow },
    ["@function.builtin.java"] = { fg = C.cyan, italic = true },
    ["@function.java"] = { fg = C.yellow },
    ["@variable.parameter.java"] = { fg = C.pink },
    ["@variable.member.java"] = { fg = C.white },
    ["@variable.builtin.java"] = { fg = C.orange, italic = true },
    ["@field.java"] = { fg = C.white },
    ["@property.java"] = { fg = C.white },
    ["@string.java"] = { fg = C.sun },
    ["@constant.java"] = { fg = C.orange },
    ["@constant.builtin.java"] = { fg = C.orange },
    ["@number.java"] = { fg = C.orange },
    ["@boolean.java"] = { fg = C.orange },
    ["@annotation.java"] = { fg = C.purple, italic = true },
    ["@operator.java"] = { fg = C.purple },
    ["@punctuation.delimiter.java"] = { fg = C.purple },
    ["@exception.java"] = { fg = C.pink, bold = true },
    ["@conditional.java"] = { fg = C.purple },
    ["@repeat.java"] = { fg = C.purple },
    -- JavaScript
    ["@keyword.import.javascript"] = { fg = C.purple, italic = true },
    ["@keyword.export.javascript"] = { fg = C.purple, italic = true },
    ["@keyword.return.javascript"] = { fg = C.purple, bold = true },
    ["@keyword.javascript"] = { fg = C.purple, italic = true },
    ["@type.javascript"] = { fg = C.cyan },
    ["@type.builtin.javascript"] = { fg = C.teal },
    ["@constructor.javascript"] = { fg = C.pink, bold = true },
    ["@function.javascript"] = { fg = C.yellow },
    ["@function.call.javascript"] = { fg = C.yellow },
    ["@function.builtin.javascript"] = { fg = C.cyan, italic = true },
    ["@variable.parameter.javascript"] = { fg = C.pink },
    ["@variable.member.javascript"] = { fg = C.white },
    ["@variable.builtin.javascript"] = { fg = C.orange, italic = true },
    ["@string.javascript"] = { fg = C.sun },
    ["@number.javascript"] = { fg = C.orange },
    ["@boolean.javascript"] = { fg = C.orange },
    ["@constant.javascript"] = { fg = C.orange },
    ["@constant.builtin.javascript"] = { fg = C.orange },
    ["@operator.javascript"] = { fg = C.purple },
    ["@punctuation.delimiter.javascript"] = { fg = C.purple },
    ["@conditional.javascript"] = { fg = C.purple },
    ["@repeat.javascript"] = { fg = C.purple },
    -- TypeScript
    ["@keyword.import.typescript"] = { fg = C.purple, italic = true },
    ["@keyword.export.typescript"] = { fg = C.purple, italic = true },
    ["@keyword.return.typescript"] = { fg = C.purple, bold = true },
    ["@keyword.typescript"] = { fg = C.purple, italic = true },
    ["@keyword.function.typescript"] = { fg = C.purple, italic = true },
    ["@type.typescript"] = { fg = C.cyan },
    ["@type.builtin.typescript"] = { fg = C.teal },
    ["@class.typescript"] = { fg = C.cyan },
    ["@constructor.typescript"] = { fg = C.pink, bold = true },
    ["@function.typescript"] = { fg = C.yellow },
    ["@function.call.typescript"] = { fg = C.yellow },
    ["@function.builtin.typescript"] = { fg = C.cyan, italic = true },
    ["@variable.parameter.typescript"] = { fg = C.pink },
    ["@variable.member.typescript"] = { fg = C.white },
    ["@variable.builtin.typescript"] = { fg = C.orange, italic = true },
    ["@string.typescript"] = { fg = C.sun },
    ["@number.typescript"] = { fg = C.orange },
    ["@boolean.typescript"] = { fg = C.orange },
    ["@constant.typescript"] = { fg = C.orange },
    ["@constant.builtin.typescript"] = { fg = C.orange },
    ["@operator.typescript"] = { fg = C.purple },
    ["@punctuation.delimiter.typescript"] = { fg = C.purple },
    ["@conditional.typescript"] = { fg = C.purple },
    ["@repeat.typescript"] = { fg = C.purple },
    -- JavaScript React (JSX)
    ["@tag.jsx"] = { fg = C.purple },
    ["@tag.attribute.jsx"] = { fg = C.pink },
    ["@tag.delimiter.jsx"] = { fg = C.purple },
    ["@property.jsx"] = { fg = C.white },
    ["@string.jsx"] = { fg = C.sun },
    ["@constant.jsx"] = { fg = C.orange },
    ["@function.jsx"] = { fg = C.yellow },
    ["@keyword.jsx"] = { fg = C.purple, italic = true },
    -- TypeScript React (TSX)
    ["@keyword.import.tsx"] = { fg = C.purple, italic = true },
    ["@keyword.export.tsx"] = { fg = C.purple, italic = true },
    ["@keyword.return.tsx"] = { fg = C.purple, bold = true },
    ["@keyword.tsx"] = { fg = C.purple, italic = true },
    ["@function.tsx"] = { fg = C.yellow },
    ["@type.tsx"] = { fg = C.cyan },
    ["@class.tsx"] = { fg = C.cyan },
    ["@string.tsx"] = { fg = C.sun },
    ["@variable.tsx"] = { fg = C.white },
    -- HTML
    ["@tag.html"] = { fg = C.purple },
    ["@tag.attribute.html"] = { fg = C.pink },
    ["@tag.delimiter.html"] = { fg = C.purple },
    ["@string.html"] = { fg = C.sun },
    ["@constant.html"] = { fg = C.orange },
    -- CSS / SCSS
    ["@property.css"] = { fg = C.white },
    ["@property.id.css"] = { fg = C.cyan },
    ["@property.class.css"] = { fg = C.cyan },
    ["@string.css"] = { fg = C.sun },
    ["@number.css"] = { fg = C.orange },
    ["@type.css"] = { fg = C.cyan },
    ["@function.css"] = { fg = C.yellow },
    ["@keyword.css"] = { fg = C.purple, italic = true },
    -- JSON / YAML
    ["@property.json"] = { fg = C.white },
    ["@string.json"] = { fg = C.sun },
    ["@number.json"] = { fg = C.orange },
    ["@boolean.json"] = { fg = C.orange },
    ["@field.yaml"] = { fg = C.white },
    ["@string.yaml"] = { fg = C.sun },
    ["@number.yaml"] = { fg = C.orange },
    ["@boolean.yaml"] = { fg = C.orange },

    -- Go / Golang
    ["@keyword.import.go"] = { fg = C.purple, italic = true },
    ["@keyword.package.go"] = { fg = C.purple, italic = true },
    ["@keyword.return.go"] = { fg = C.purple, bold = true },
    ["@keyword.go"] = { fg = C.purple, italic = true },
    ["@keyword.function.go"] = { fg = C.purple, italic = true },
    ["@keyword.operator.go"] = { fg = C.purple },
    ["@type.go"] = { fg = C.cyan },
    ["@type.builtin.go"] = { fg = C.teal },
    ["@struct.go"] = { fg = C.cyan },
    ["@interface.go"] = { fg = C.cyan, italic = true },
    ["@constructor.go"] = { fg = C.pink, bold = true },
    ["@function.go"] = { fg = C.yellow },
    ["@function.call.go"] = { fg = C.yellow },
    ["@function.builtin.go"] = { fg = C.cyan, italic = true },
    ["@method.go"] = { fg = C.yellow },
    ["@method.call.go"] = { fg = C.yellow },
    ["@variable.parameter.go"] = { fg = C.pink },
    ["@variable.member.go"] = { fg = C.white },
    ["@variable.builtin.go"] = { fg = C.orange, italic = true },
    ["@field.go"] = { fg = C.white },
    ["@property.go"] = { fg = C.white },
    ["@string.go"] = { fg = C.sun },
    ["@constant.go"] = { fg = C.orange },
    ["@constant.builtin.go"] = { fg = C.orange },
    ["@number.go"] = { fg = C.orange },
    ["@boolean.go"] = { fg = C.orange },
    ["@operator.go"] = { fg = C.purple },
    ["@punctuation.delimiter.go"] = { fg = C.purple },
    ["@exception.go"] = { fg = C.pink, bold = true },
    ["@conditional.go"] = { fg = C.purple },
    ["@repeat.go"] = { fg = C.purple },
    -- Rust
    ["@keyword.rust"] = { fg = C.purple, italic = true },
    ["@type.rust"] = { fg = C.cyan },
    ["@type.builtin.rust"] = { fg = C.teal },
    ["@function.rust"] = { fg = C.yellow },
    ["@function.call.rust"] = { fg = C.yellow },
    ["@macro.rust"] = { fg = C.purple },
    ["@variable.parameter.rust"] = { fg = C.pink },
    ["@variable.builtin.rust"] = { fg = C.orange, italic = true },
    ["@constant.rust"] = { fg = C.orange },
    ["@operator.rust"] = { fg = C.purple },
    ["@conditional.rust"] = { fg = C.purple },
    ["@repeat.rust"] = { fg = C.purple },
    -- Markdown
    ["@markup.heading.1.markdown"] = { fg = C.red, bold = true },
    ["@markup.heading.2.markdown"] = { fg = C.orange, bold = true },
    ["@markup.heading.3.markdown"] = { fg = C.yellow, bold = true },
    ["@markup.heading.4.markdown"] = { fg = C.purple, bold = true },
    ["@markup.heading.5.markdown"] = { fg = C.pink, bold = true },
    ["@markup.heading.6.markdown"] = { fg = C.cyan, bold = true },
    ["@markup.heading.1.marker.markdown"] = { fg = C.red, bold = true },
    ["@markup.heading.2.marker.markdown"] = { fg = C.orange, bold = true },
    ["@markup.heading.3.marker.markdown"] = { fg = C.yellow, bold = true },
    ["@markup.heading.4.marker.markdown"] = { fg = C.purple, bold = true },
    ["@markup.heading.5.marker.markdown"] = { fg = C.pink, bold = true },
    ["@markup.heading.6.marker.markdown"] = { fg = C.cyan, bold = true },
    ["@markup.strong.markdown_inline"] = { fg = C.orange, bold = true },
    ["@markup.italic.markdown_inline"] = { fg = C.white, italic = true },
    ["@markup.strikethrough.markdown_inline"] = { fg = C.dark_purple, strikethrough = true },
    ["@markup.link.label.markdown_inline"] = { fg = C.cyan },
    ["@markup.link.url.markdown_inline"] = { fg = C.cyan, underline = true },
    ["@markup.link.markdown_inline"] = { fg = C.cyan, underline = true },
    ["@markup.raw.markdown_inline"] = { fg = C.teal },
    ["@markup.raw.block.markdown"] = { fg = C.teal },
    ["@markup.quote.markdown"] = { fg = C.dark_purple, italic = true },
    ["@markup.list.checked.markdown"] = { fg = C.green },
    ["@markup.list.unchecked.markdown"] = { fg = C.red },
    ["@markup.list.markdown"] = { fg = C.yellow },
    ["@punctuation.special.markdown"] = { fg = C.purple },
    -- PHP
    ["@keyword.php"] = { fg = C.purple, italic = true },
    ["@keyword.import.php"] = { fg = C.purple, italic = true },
    ["@keyword.return.php"] = { fg = C.purple, bold = true },
    ["@keyword.function.php"] = { fg = C.purple, italic = true },
    ["@keyword.modifier.php"] = { fg = C.purple, italic = true },
    ["@type.php"] = { fg = C.cyan },
    ["@type.builtin.php"] = { fg = C.teal },
    ["@class.php"] = { fg = C.cyan },
    ["@interface.php"] = { fg = C.cyan, italic = true },
    ["@constructor.php"] = { fg = C.pink, bold = true },
    ["@function.php"] = { fg = C.yellow },
    ["@function.call.php"] = { fg = C.yellow },
    ["@function.builtin.php"] = { fg = C.cyan, italic = true },
    ["@method.php"] = { fg = C.yellow },
    ["@method.call.php"] = { fg = C.yellow },
    ["@variable.php"] = { fg = C.white },
    ["@variable.parameter.php"] = { fg = C.pink },
    ["@variable.member.php"] = { fg = C.white },
    ["@variable.builtin.php"] = { fg = C.orange, italic = true },
    ["@property.php"] = { fg = C.white },
    ["@field.php"] = { fg = C.white },
    ["@string.php"] = { fg = C.sun },
    ["@constant.php"] = { fg = C.orange },
    ["@constant.builtin.php"] = { fg = C.orange },
    ["@number.php"] = { fg = C.orange },
    ["@boolean.php"] = { fg = C.orange },
    ["@operator.php"] = { fg = C.purple },
    ["@punctuation.delimiter.php"] = { fg = C.purple },
    ["@exception.php"] = { fg = C.pink, bold = true },
    ["@conditional.php"] = { fg = C.purple },
    ["@repeat.php"] = { fg = C.purple },
    ["@tag.php"] = { fg = C.red },
    ["@namespace.php"] = { fg = C.cyan },
    -- LSP Semantic Highlights
    ["@lsp.type.class"] = { fg = C.cyan },
    ["@lsp.type.comment"] = { fg = C.dark_purple, italic = true },
    ["@lsp.type.decorator"] = { fg = C.purple, italic = true },
    ["@lsp.type.enum"] = { fg = C.cyan },
    ["@lsp.type.enumMember"] = { fg = C.orange },
    ["@lsp.type.event"] = { fg = C.yellow },
    ["@lsp.type.function"] = { fg = C.yellow },
    ["@lsp.type.interface"] = { fg = C.cyan, italic = true },
    ["@lsp.type.keyword"] = { fg = C.purple },
    ["@lsp.type.macro"] = { fg = C.purple },
    ["@lsp.type.method"] = { fg = C.yellow },
    ["@lsp.type.modifier"] = { fg = C.purple, italic = true },
    ["@lsp.type.namespace"] = { fg = C.cyan },
    ["@lsp.type.number"] = { fg = C.orange },
    ["@lsp.type.operator"] = { fg = C.purple },
    ["@lsp.type.parameter"] = { fg = C.pink },
    ["@lsp.type.property"] = { fg = C.white },
    ["@lsp.type.regexp"] = { fg = C.green },
    ["@lsp.type.string"] = { fg = C.sun },
    ["@lsp.type.struct"] = { fg = C.cyan },
    ["@lsp.type.type"] = { fg = C.teal },
    ["@lsp.type.typeParameter"] = { fg = C.pink },
    ["@lsp.type.variable"] = { fg = C.white },
    ["@lsp.mod.abstract"] = { bold = true },
    ["@lsp.mod.async"] = { italic = true },
    ["@lsp.mod.declaration"] = { bold = true },
    ["@lsp.mod.defaultLibrary"] = { fg = C.yellow },
    ["@lsp.mod.definition"] = { underline = false },
    ["@lsp.mod.deprecated"] = { strikethrough = true },
    ["@lsp.mod.documentation"] = { fg = C.dark_purple, italic = true },
    ["@lsp.mod.modification"] = { underline = true },
    ["@lsp.mod.readonly"] = { fg = C.orange },
    ["@lsp.mod.static"] = { bold = true },
  },
}
M.type = "dark"
M = require("base46").override_theme(M, "samtone")
return M
