return {
  {
    "mason-org/mason.nvim",
    opts = {
      ensure_installed = {
        "jdtls",
        "prettier",

        "bash-language-server",
        "codelldb",
        "delve",
        "gofumpt",
        "goimports",
        "golangci-lint",
        "gomodifytags",
        "gopls",
        "impl",
        "json-lsp",
        "lua-language-server",
        "markdown-toc",
        "marksman",
        "pyright",
        "rust-analyzer",
        "shellcheck",
        "shfmt",
        "stylua",
        "tailwindcss-language-server",
        "tree-sitter-cli",
        "vtsls",
        "vue-language-server",
        "rust-analyzer",
      },
    },
  },
}
